version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/core
      - ./static:/app/static
      - ./media:/app/media
    ports:
    - "8015:8015"
    command: bash -c "python manage.py migrate && gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8015"